export { createAuthServer } from "./auth-server";
export type { AuthServer } from "./auth-server";
export { createClient } from "./auth-client";
export { workspacePlugin } from "./plugins";
export { createEmailPasswordProvider } from "./providers/email-password";
export type { EmailPasswordProvider } from "./providers/email-password";
export { createOAuthProviders } from "./providers/oauth";
export type { OAuthProviders, OAuthConfig, OAuthProviderConfig } from "./providers/oauth";
export { createAuthService } from "./services/auth-service";
export type { AuthService, AuthServiceResult, RegisterResult, LoginResult, VerifyEmailResult, ForgotPasswordResult, ResetPasswordResult } from "./services/auth-service";
export { createPasswordResetService } from "./services/password-reset-service";
export type { PasswordResetService, PasswordResetResult } from "./services/password-reset-service";
export { createMFAService } from "./services/mfa-service";
export type { MFAService, MFASetupResult } from "./services/mfa-service";
export { generateTOTPSecret, generateTOTPUri, generateQRCodeDataUrl, verifyTOTPCode } from "./services/totp";
export { generateRecoveryCodes, hashRecoveryCode, hashRecoveryCodes, verifyRecoveryCode } from "./services/recovery-codes";
export { createOAuthService } from "./services/oauth-service";
export type { OAuthService, OAuthServiceResult, LinkAccountResult, UnlinkAccountResult } from "./services/oauth-service";
export { createSessionCache } from "./services/session-cache";
export type { SessionCache, CachedSession } from "./services/session-cache";
export { createSessionService } from "./services/session-service";
export type { SessionService, SessionServiceMethods, SessionInfo, VerifySessionResult } from "./services/session-service";
export { createWorkspaceService } from "./services/workspace-service";
export type { WorkspaceService, WorkspaceServiceMethods, WorkspaceServiceResult } from "./services/workspace-service";
export { sendVerificationEmail, buildVerificationEmailUrl } from "./emails/verification-email";
export type { VerificationEmailParams } from "./emails/verification-email";
export { sendWelcomeEmail } from "./emails/welcome-email";
export type { WelcomeEmailParams } from "./emails/welcome-email";
export { sendPasswordResetEmail, buildPasswordResetUrl, extractResetToken } from "./emails/password-reset-email";
export type { PasswordResetEmailParams } from "./emails/password-reset-email";
export { PERMISSIONS } from "./rbac/permissions";
export type { Permission } from "./rbac/permissions";
export { ROLE_HIERARCHY, ROLE_PERMISSIONS, roleHasPermission, roleAtLeast } from "./rbac/roles";
export type { WorkspaceRole } from "./rbac/roles";
export { createPermissionCache } from "./rbac/cache";
export type { PermissionCache, PermissionCacheMethods } from "./rbac/cache";
export { createRBACService } from "./rbac/service";
export type { RBACService, RBACServiceMethods, GetUserRoleFn } from "./rbac/service";
export { requirePermission, setRBACService } from "./rbac/require-permission";
export type { PermissionGuard } from "./rbac/require-permission";
export { usePermissions, useSetPermissions } from "./hooks/use-permissions";
export { sendInvitationEmail } from "./emails/invitation-email";
export type { InvitationEmailParams } from "./emails/invitation-email";
export { createInvitationService } from "./services/invitation-service";
export type { InvitationService, InvitationServiceResult, InvitationServiceMethods } from "./services/invitation-service";
